name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          npm install
          npm run build
          git config --global user.name 'Anurag Guha'
          git config --global user.email 'rick.anurag2@gmail.com'
          git checkout -b gh-pages
          mv build/* .
          rm -rf build
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
